Repository laminas/laminas-navigation, pull requests merged in 2021-04, with the labels that each got.

#15 Add GHA CI workflow
  .gitattributes
  .github/workflows/continuous-integration.yml
  .gitignore
  .travis.yml
  CHANGELOG.md
  README.md
  composer.lock
Labels: Enhancement

#14 Adds cookbook recipe for creating a XML sitemap in mvc-based application
  docs/book/cookbook/mvc-sitemap.md
  mkdocs.yml
Labels: Documentation, Enhancement

#13 Adds page and configuration for installation
  docs/book/installation.md
  mkdocs.yml
Labels: Documentation, Enhancement

#16 Fixes Markdown problems in documentation files
  docs/book/cookbook/mvc-sitemap.md
  docs/book/helpers/intro.md
  docs/book/helpers/links.md
  docs/book/helpers/menu.md
  docs/book/helpers/sitemap.md
Labels: Bug

#17 Updates cookbook recipe for sitemap to use laminas-mvc-middleware v2
  docs/book/cookbook/mvc-sitemap.md
Labels: Bug
